apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api
  name: api-dev-rolebinding-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: 80c0882f-6560-40c4-8725-f3bc5474a964
  apiGroup: rbac.authorization.k8s.io
  namespace: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api
  name: api-dev-rolebinding-view
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: 80c0882f-6560-40c4-8725-f3bc5474a964
  apiGroup: rbac.authorization.k8s.io
  namespace: api
