apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  secretObjects:
    - data:
        - key: SQL_USER
          objectName: SQL_USER
        - key: SQL_PASSWORD
          objectName: SQL_PASSWORD
        - key: SQL_SERVER
          objectName: SQL_SERVER
        - key: SQL_DBNAME
          objectName: SQL_DBNAME
      secretName: tripkeys
      type: Opaque
                
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "47c06f59-f13c-40c7-aab2-afe3568127f5" 
    keyvaultName: "tripkv1"
    objects:  |
      array:
        - |
          objectName: sqluser
          objectType: secret
          objectAlias: SQL_USER
        - |
          objectName: sqlpassword
          objectType: secret
          objectAlias: SQL_PASSWORD
        - |
          objectName: sqlserver
          objectType: secret
          objectAlias: SQL_SERVER
        - |
          objectName: sqldb
          objectType: secret
          objectAlias: SQL_DBNAME
    tenantId: ""