apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-deployment
  namespace: api
  labels:
    deploy: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: "registryklg3329.azurecr.io/trips:1.0"
        imagePullPolicy: Always
        name: trips   
        livenessProbe:
          httpGet:
            path: /api/trips/healthcheck
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/trips/healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        env:
          - name: PORT
            value: '80'
          - name: OPENAPI_DOCS_URI
            value: 'http://localhost'
          - name: DEBUG_LOGGING
            value: 'true'
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: tripkeys
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tripkeys
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: tripkeys
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: tripkeys
                key: SQL_DBNAME
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
    - protocol: TCP
      name: trips-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: trips-https
      port: 443
      targetPort: 443