apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web
  name: web-dev-rolebinding-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: df3e6cb0-5231-4b55-8589-c95b3893fb9d
  apiGroup: rbac.authorization.k8s.io
  namespace: web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web
  name: web-dev-rolebinding-view
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: df3e6cb0-5231-4b55-8589-c95b3893fb9d
  apiGroup: rbac.authorization.k8s.io
  namespace: web
