apiVersion: v1
kind: Secret
metadata:
  name: sql
  namespace: api
type: Opaque
data:
  SQL_USER: c3FsYWRtaW5nV2EzNTE3
  SQL_PASSWORD: dkc0a3AyUXQ1
  SQL_SERVER: c3Fsc2VydmVyZ3dhMzUxNw==
  SQL_DBNAME: bXlkcml2aW5nREI=